// React/project/shop-admin-react/src/routes/login.jsx
import { Col, Row, Form, Input, Button, message } from 'antd'
import { LockOutlined, UserOutlined } from '@ant-design/icons'
import { useState, useEffect } from 'react'
import { login, getinfo } from '../api/manager.js'
import { useNavigate } from 'react-router-dom'
import { useMyToken } from '../composables/auth.jsx'
import { useBearStore } from '../store/index.jsx'

const SubmitButton = ({ form, loading }) => {
  const [submittable, setSubmittable] = useState(false)
  const [messageApi, contextHolder] = message.useMessage()

  const values = Form.useWatch([], form)
  useEffect(() => {
    form
      .validateFields({
        validateOnly: true,
      })
      .then(
        () => {
          setSubmittable(true)
        },
        () => {
          setSubmittable(false)
        },
      )
  }, [values])
  return (
    <>
      {contextHolder}
      <Button
        type="primary"
        htmlType="submit"
        disabled={!submittable}
        style={{ width: '250px' }}
        loading={loading}
        onClick={() => {
          if (form.getFieldsValue().username == 'admin' && form.getFieldsValue().password == 'admin') {
            messageApi.open({
              type: 'success',
              content: '登陆成功',
            })
          } else {
            messageApi.open({
              type: 'error',
              content: '用户名或密码错误',
            })
          }
        }}
      >
        登录
      </Button>
    </>
  )
}

export default function Login() {
  const [loading, setLoading] = useState(false)
  const [form] = Form.useForm()
  const navigate = useNavigate()
  const { setToken } = useMyToken()
  const [user, setUser] = useBearStore((state) => [state.user, state.setUser])

  return (
    <Row className=" bg-indigo-500 min-h-screen">
      <Col lg={16} md={12} className=" flex flex-col items-center justify-center">
        <div className=" font-bold text-5xl text-lime-50 mb-4">欢迎光临</div>
        <div className=" text-gray-200 text-sm">React+Vite+Antd+TailWindCSS+React Router+Zustand实战</div>
      </Col>
      <Col lg={8} md={12} className=" flex items-center justify-center bg-lime-50 flex-col">
        <h2 className=" font-bold text-gray-800 text-3xl">欢迎回来</h2>
        <div className=" flex items-center justify-center my-5 text-gray-300 space-x-2">
          <span className=" w-16 bg-gray-200" style={{ height: '1px' }}></span>
          <span>账号密码登录</span>
          <span className=" w-16 bg-gray-200" style={{ height: '1px' }}></span>
        </div>
        <Form
          name="basic"
          initialValues={{
            remember: true,
          }}
          style={{ width: '250px' }}
          autoComplete="off"
          form={form}
          onFinish={(values) => {
            setLoading(true)
            login(values.username, values.password)
              .then((res) => {
                navigate('/home')
                setToken(res.data.data.token)
                getinfo().then((result) => {
                  setUser(result.data.data)
                })
              })
              .finally(() => {
                setLoading(false)
              })
          }}
        >
          <Form.Item
            name="username"
            rules={[
              {
                required: true,
                message: '请输入用户名!',
              },
            ]}
          >
            <Input placeholder="Username" prefix={<UserOutlined className=" opacity-30" />} />
          </Form.Item>

          <Form.Item
            name="password"
            rules={[
              {
                required: true,
                message: '请输入密码!',
              },
            ]}
          >
            <Input.Password prefix={<LockOutlined className=" opacity-30" />} type="password" placeholder="Password" />
          </Form.Item>

          <Form.Item>
            <SubmitButton form={form} loading={loading} />
          </Form.Item>
        </Form>
      </Col>
    </Row>
  )
}

// Vue/project/shop-admin/src/pages/login.vue
<template>
  <el-row class="login-container">
    <el-col :lg="16" :md="12" class="left ">
      <div>
        <div>欢迎光临</div>
        <div>此站点是Vue3+Vite实战项目,马场郭德纲在线教学,开始学习</div>
      </div>
    </el-col>

    <el-col :lg="8" :md="12" class="right">
      <h2 class="title">欢迎回来</h2>
      <div>
        <span class="line"> </span>
        <span>账号密码登录</span>
        <span class="line"> </span>
      </div>
      <el-form :model="form" :rules="formRules" ref="formRef" class="w-[250px]">
        <el-form-item prop="username">
          <el-input v-model="form.username" placeholder="请输入用户名">
            <template #prefix>
              <el-icon>
                <User />
              </el-icon>
            </template>
          </el-input>
        </el-form-item>
        <el-form-item prop="password">
          <el-input v-model="form.password" type="password" placeholder="请输入密码" show-password>
            <template #prefix>
              <el-icon>
                <lock />
              </el-icon>
            </template>
          </el-input>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onSubmit" class="w-[250px]" round color="#626aef" :loading="loading">登 录</el-button>
        </el-form-item>
      </el-form>
    </el-col>
  </el-row>
</template>

<script setup>
import { reactive, ref, onMounted, onBeforeUnmount } from 'vue'
import { toast } from '~/composables/util.js'
import { useRouter } from 'vue-router'
import { useStore } from 'vuex'

const router = useRouter()
const store = useStore()

const form = reactive({
  username: '',
  password: '',
})

const formRules = {
  username: [
    { required: true, message: '用户名不能为空', trigger: 'blur' },
    { min: 3, max: 5, message: '用户名长度必须在3到5个字符', trigger: 'blur' },
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 5, max: 15, message: 'Length should be 5 to 15', trigger: 'blur' },
  ],
}

const formRef = ref(null)
const loading = ref(false)

const onSubmit = () => {
  // this.$ref.validate()是Vue组件验证表单的内置方法
  formRef.value.validate((valid) => {
    if (!valid) {
      return false
    }
    loading.value = true
    store
      .dispatch('login', form)
      .then((res) => {
        toast('登陆成功', 'success')
        router.push('/')
      })
      .finally(() => {
        loading.value = false
      })
  })
}

// 监听回车事件
function onKeyUp(e) {
  if (e.key == 'Enter') {
    onSubmit()
  }
}
onMounted(() => {
  document.addEventListener('keyup', onKeyUp)
})
onBeforeUnmount(() => {
  document.removeEventListener('keyup', onKeyUp)
})
</script>

<style scoped>
.login-container {
  @apply bg-indigo-500 min-h-screen;
}
.left,
.right {
  @apply flex items-center justify-center;
}
.right {
  @apply bg-light-50 flex-col;
}
.left > div > div:first-child {
  @apply font-bold text-5xl text-light-50 mb-4;
}
.left > div > div:last-child {
  @apply text-gray-200 text-sm;
}
.right .title {
  @apply font-bold text-gray-800 text-3xl;
}
.right > div {
  @apply flex items-center justify-center my-5 text-gray-300 space-x-2;
}
.right div .line {
  @apply h-[1px] w-16 bg-gray-200;
}
</style>
